language: cpp

branches:
  only:
   - master

before_install:
  - arch
  - sudo ls /etc/dpkg/dpkg.cfg.d/
  - sudo sh -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
  - sudo ls /etc/dpkg/dpkg.cfg.d/
#  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install nasm:i386 gcc-multilib g++-multilib paxctl:i386
script:
  - cd src/tomcrypt
  - ./compile_linux.sh
  - cd ../mbedtls
  - make
  - cd ../..
  - ./build_updateable_elf.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FsHPkowl4oZSLUhfEr7Q2sMGiNSJqJ4SAjRYxzh7o6/luf06gsq4WAXbZS6tEgCJJrpo//vjJIXQkyjY5wvovl8g25DESyyFNrY86adx5PRFz2zEgocZ4koQp883VBQC0cRBKHLsh8hL/GZ5j8aQhvGCN5lMWHQjNJlGPU06HXAZAZLTmYoU9JaMEIbksFiZtXWMBIGUFhDVmCCwTQwig/+jGKfPi0YAkUTVrQ/tvq8glymK/CYZtipeDYPXAKFdJfVfgLRxCTDpThM56mH9vj28DrQHUFL9ivIAc4B+2H3E0N8qjv6Xb0kIQuMqqn3Q0n7zM1t0uKJXXo/zA/7DyR8E4JEuR1PAFjSb3Tyt3FObwZM2FzL+IsXuf9x0ozEUKujY9YWn+o4+usBWB9z/i87f7e+9yYdTxbXAGEQLP7w7gDlpJlWMHHJ8j5WDvbS3j7T5xokjzJLrxbmZc1TdrKqMXrIV5ryAecHZJkiA1ccK9+ukPtCYXN8V/u0yHTS5UGaQn96R935yk2VLjwzEE7muTLExFZRxXR2cVuM0XpBMJDtija3zxpBhk+4wuzyvbq+4fhA3iDm2tKVOfa9s3uR/s4HJgIitIidZyYRKrsrNYujNDBAvoVWDlgXe0OQTqJHvgTJqMUHbTHNwvhzQaTDCwV6OtaGPGvJsabYTefQ=
  file: ./bin/cod4x18_dedrun
  on:
    tags: true
#    all_branches: true
    #repo: D4edalus/CoD4x1.8_Server_Pub
