version: 1.0.{build}
before_build:
- ps: >-
    choco install -y mingw -x86

    ls "C:/tools"
    
    ls "C:/tools/mingw32"
    
    ls "C:/tools/mingw32/bin"
    
    Write-Host "    Downloading pexports..."
    
    curl -o "pexports.tar.xz" "https://github.com/callofduty4x/CoD4x_Server/raw/master/tools/pexports-0.47-mingw32-bin.tar.xz"
    
    Write-Host "    Installing pexports..."

    7z x pexports.tar.xz | Out-Null

    7z x pexports.tar | Out-Null

    Write-Host "Setting up NASM:"
    
    Write-Host "    Downloading NASM..."
    
    curl -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe
    
    Write-Host "    Installing NASM..."
    
    .\nasminst.exe /S
    
    Write-Host "Setting up environment variables."
    
    [Environment]::SetEnvironmentVariable("PATH",  "C:\tools\mingw32\bin;$pwd\bin;C:\Program Files (x86)\nasm;$($env:path)")

build_script:
- cmd: >-
    echo "Building server code:"
    
    mingw32-make.exe
    
    mingw32-make.exe DEBUG=true

    Write-Host "Done."
    
    cd plugins && build_plugins.cmd && cd ..
    
    echo "Done."
test_script:
- ps: ./bin/cod4x18_dedrun.exe
branches:
  only:
    - master    # Ignore all other branches.
    - dev_newarch
artifacts: 
  - path: bin\cod4x18_dedrun.exe
    name: cod4exe
    
  - path: bin\cod4x18_dedrun_dbg.exe
    name: cod4exe_dbg

  - path: plugins\**\*.dll
    name: plugins
deploy:
- provider: GitHub
  auth_token:
    secure: Je7YohhSVawAyVkWQG3zyoppIB73CjJB99IlzzJzosFJ5NeBkYLUuA2SV52LTWXj
  artifact: cod4exe, cod4exe_dbg, plugins
  draft: false
  prerelease: false
  force_update: true
  on:
    #branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
